export default function TermsOfService() {
  return (
    <div className="container">
      <div className="info-page">
        <h1>Terms of Service</h1>
        <span className="updated">Last updated: January 2025</span>

        <p>
          By accessing or using ToolBox ("the site"), you agree to be bound by these Terms of Service. If you do
          not agree with any part of these terms, please do not use the site.
        </p>

        <h2>1. Use of the Site</h2>
        <p>
          ToolBox provides free, browser-based utility tools for personal and professional use. You may use these
          tools for any lawful purpose. You agree not to use the site in any way that violates applicable laws or
          regulations, infringes any intellectual property rights, or attempts to interfere with the site's
          operation.
        </p>

        <h2>2. No Warranties</h2>
        <p>
          The tools and content on ToolBox are provided "as is" without warranties of any kind, either express or
          implied. We do not warrant that the tools will be accurate, error-free, or uninterrupted. You use the
          tools at your own risk. We are not responsible for any actions you take based on output from these tools.
        </p>

        <h2>3. Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, ToolBox and its operators shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages arising from your use of the site or its tools.
          Our total liability to you for any claim shall not exceed the amount you paid us in the twelve months
          preceding the claim (which in most cases will be zero, as the site is free).
        </p>

        <h2>4. Intellectual Property</h2>
        <p>
          The design, code, and written content of ToolBox are the intellectual property of the site operators.
          You may not reproduce, distribute, or create derivative works from any part of this site without express
          written permission. The output generated by our tools (e.g., generated usernames, formatted JSON) is
          yours to use freely.
        </p>

        <h2>5. Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. The "last updated" date will reflect changes.
          Continued use of the site after modifications constitutes acceptance of the revised terms.
        </p>

        <h2>6. Governing Law</h2>
        <p>
          These terms are governed by and construed in accordance with applicable law. Any disputes shall be
          resolved in the appropriate courts of the applicable jurisdiction.
        </p>

        <h2>7. Contact</h2>
        <p>
          Questions about these terms? Reach us at{' '}
          <a href="mailto:conradbusa@gmail.com">conradbusa@gmail.com</a>.
        </p>
      </div>
    </div>
  );
}
